/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Subtitle = string;
export type XAxisLabel = string;
export type YAxisLabel = string;
export type HorizontalBars = boolean;
/**
 * When multiple charts are drawn, then they will be layed out horizontically or vertically.
 */
export type VerticalChartLayout = boolean;
/**
 * The name for this data series
 */
export type Label = string;
/**
 * If two dataseries have the same 'Chart' name, they will be drawn in the same chart. Otherwise they will get their own chart. If the name ends with #pivot# then a separat chart will be drawn for each pivoted dataseries.
 */
export type Chart = string;
/**
 * To stack series on top of each other within one chart, give them the same stack name.
 */
export type Stack = string;
/**
 * The Thickness of the bar in pixels
 */
export type BarThickness = number;
/**
 * The inner color of the bars.
 */
export type BarColor = string;
/**
 * The border color of the bars.
 */
export type BorderColor = string;
export type BorderWidth = number;
/**
 * Number in pixels for a rounding effect on the bars.
 */
export type BarCornerRadius = number;
/**
 * You can specify a column in the input data to autogenerate dataseries for each distinct entry in this column. E.g. if you have a table with columns [city, timestamp, temperature] and specify 'city' as pivot column, then you will get a line for each city.
 */
export type PivotColumn = string;
/**
 * The data used to draw this data series.
 */
export type Data = {
  x: string;
  y: string;
  pivot?: PivotColumn;
  [k: string]: unknown;
}[];
export type Dataseries = {
  label: Label;
  chartName?: Chart;
  stack?: Stack;
  barThickness?: BarThickness;
  backgroundColor?: BarColor;
  borderColor?: BorderColor;
  borderWidth?: BorderWidth;
  borderRadius?: BarCornerRadius;
  data?: Data;
  [k: string]: unknown;
}[];

export interface ConfigureTheBarChart {
  settings?: GlobalSettings;
  dataseries?: Dataseries;
  [k: string]: unknown;
}
export interface GlobalSettings {
  title?: Title;
  subTitle?: Subtitle;
  xAxisLabel?: XAxisLabel;
  yAxisLabel?: YAxisLabel;
  horizontal?: HorizontalBars;
  columnLayout?: VerticalChartLayout;
  [k: string]: unknown;
}
